packages:
  - "packages/api/**"
  - "packages/shared/**"
  - "packages/desktop-app/**"
  - "packages/web-app/**"
  - "packages/admin-app/**"
  - "packages/native-app/**"
  - "packages/web-design-sandbox/**"
  - "packages/web-ui/**"
  - "packages/native-ui/**"
